### ISSUE TITLE
[CHORE] entity 설정

### ISSUE THREAD

**Issue by goseungwon** [KUSITMS-4GATE/Groad-Server#8]
## IssueName

[CHORE] Entity 설정

## Description

Entity 설정

## Todo

- [ ] BaseEntity 작성
- [ ] 각 도메인별 Entity 작성
- [ ] Entity SoftDelete로 설정

**Comment by dl-00-e8** [comment]
Entity 구현 과정에서는 ddl-auto를 update로 변경하여 정상적으로 생성되는지 확인 후, Entity 개발이 끝나면 ddl-auto를 validate로 변경하여 관리하는 것이 Entity와 Table 매핑에 용이하다고 판단하여 변경하여 작업 진행했습니다.

**Comment by dl-00-e8** [comment]
[이 글](https://www.baeldung.com/hibernate-notnull-vs-nullable)을 참고하여 nullable 옵션을 쓰는 것보다 NotNull 어노테이션을 쓰는 것이 쿼리 요청 전에 예외 확인이 가능하므로 좋다고 판단하여 해당 방식 적용했습니다.

**Comment by goseungwon** [comment]
> [이 글](https://www.baeldung.com/hibernate-notnull-vs-nullable) 을 참고하여 nullable 옵션을 쓰는 것보다 NotNull 어노테이션을 쓰는 것이 쿼리를 요청하기 전에 취소가 가능하면 항상 저장하여 적용 방식을 적용했습니다.

`@NotNull` 어노테이션으로 null값을 방지하는게 쿼리를 날리기 전에 확인해주기 때문에 더 효율적인 방법같군요 좋습니다.

다만 나중에 한 테이블을 여러 어플리케이션에서 사용하는 환경이 생긴다면 조심해야겠군요
